LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := apns-conf.xml
LOCAL_MODULE_CLASS := ETC

DEFAULT_APNS_FILE := vendor/syberia/prebuilt/etc/apns-conf.xml

ifdef CUSTOM_APNS_FILE
CUSTOM_APNS_SCRIPT := vendor/syberia/tools/custom_apns.py
FINAL_APNS_FILE := $(local-generated-sources-dir)/apns-conf.xml

$(FINAL_APNS_FILE): PRIVATE_SCRIPT := $(CUSTOM_APNS_SCRIPT)
$(FINAL_APNS_FILE): PRIVATE_CUSTOM_APNS_FILE := $(CUSTOM_APNS_FILE)
$(FINAL_APNS_FILE): $(CUSTOM_APNS_SCRIPT) $(DEFAULT_APNS_FILE)
	rm -f $@
	python $(PRIVATE_SCRIPT) $@ $(PRIVATE_CUSTOM_APNS_FILE)
else
FINAL_APNS_FILE := $(DEFAULT_APNS_FILE)
endif

LOCAL_PREBUILT_MODULE_FILE := $(FINAL_APNS_FILE)

LOCAL_PRODUCT_MODULE := true

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Changelog.txt
LOCAL_MODULE_CLASS := ETC
CHANGELOG_FILE := $(local-generated-sources-dir)/Changelog.txt
CHANGELOG_SCRIPT := vendor/syberia/tools/changelog
$(CHANGELOG_FILE): PRIVATE_CHANGELOG_SCRIPT := $(CHANGELOG_SCRIPT)
$(CHANGELOG_FILE): PRIVATE_CHANGELOG_FILE := $(CHANGELOG_FILE)
$(CHANGELOG_FILE): $(PRIVATE_CHANGELOG_SCRIPT) $(PRIVATE_CHANGELOG_FILE)
	@echo "Generating Changelog"
	$(shell $(PRIVATE_CHANGELOG_SCRIPT) $(PRIVATE_CHANGELOG_FILE))

LOCAL_PREBUILT_MODULE_FILE := $(CHANGELOG_FILE)
include $(BUILD_PREBUILT)
