# Versioning System
SYBERIA_VERSION = v1.0

ifndef SYBERIA_BUILD_TYPE
    SYBERIA_BUILD_TYPE := OFFICIAL
endif

# Set all versions
DATE := $(shell date -u +%Y%m%d-%H%M)
TARGET_BACON_NAME := $(TARGET_PRODUCT)-$(SYBERIA_VERSION)-$(DATE)-$(SYBERIA_BUILD_TYPE)
SYBERIA_FINGERPRINT := Syberia/$(SYBERIA_VERSION)/$(PLATFORM_VERSION)/$(BUILD_ID)/$(DATE)

PRODUCT_PROPERTY_OVERRIDES += \
    BUILD_DISPLAY_ID=$(BUILD_ID) \
    ro.syberia.version=$(SYBERIA_VERSION) \
    ro.mod.version=$(SYBERIA_BUILD_TYPE)-$(SYBERIA_VERSION)-$(DATE) \
    com.syberia.fingerpring=$(SYBERIA_FINGERPRINT)