#!/bin/sh

# Exports

#. $ANDROID_BUILD_TOP/vendor/syberia/tools/colors

export Changelog=Changelog.txt

if [ -f $Changelog ];
then
	rm -f $Changelog
fi

touch $Changelog

# Print something to build output
echo ${bldppl}"Generating changelog..."${txtrst}

for i in $(seq 7);
do
export After_Date=`date --date="$i days ago" +%F`
k=$(expr $i - 1)
export Until_Date=`date --date="$k days ago" +%F`
echo "=============" >> $Changelog;
echo "   $Until_Date" >> $Changelog;
echo "=============" >> $Changelog;
while read path;
    do
    # https://www.cyberciti.biz/faq/unix-linux-bash-script-check-if-variable-is-empty/
    Git_log=`git --git-dir ${path}/.git log --after=$After_Date --until=$Until_Date --pretty=tformat:"%h  %s  [%an]" --abbrev-commit --abbrev=7`
    if [ ! -z "${Git_log}" ]; then
    echo "\n[* ${path} *]\n${Git_log}\n" >> $Changelog;
    fi
done < .repo/project.list;

echo "" >> $Changelog;
done

cp $Changelog $OUT/system/etc/
cp $Changelog $OUT/
rm $Changelog